# Intro


Live et exercices créés par Phuong Nguyen:

[Linkedin](https://www.linkedin.com/in/fphuongnguyen/)

[Newsletter](https://sundayselectstar.substack.com/)

Pour monter en compétences en SQL et résoudre des problèmes business concrets:
https://accelerateur-data.systeme.io/accelerateur-sql

# Téléchargement du dataset dans DuckDB

Lien du dataset: https://www.kaggle.com/datasets/bhanuthakurr/cleaned-contoso-dataset/data

Exécutez toutes les cellules dans cette partie pour un setup complet.

In [1]:
%pip install duckdb-engine --quiet

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.7/49.7 kB 1.7 MB/s eta 0:00:00

In [2]:
import sys
import pandas as pd
import duckdb
import matplotlib.pyplot as plt
%matplotlib inline

if 'google.colab' in sys.modules:
    !sudo apt-get update -qq > /dev/null 2>&1
    !pip install -q duckdb > /dev/null 2>&1
    !pip install -q kagglehub > /dev/null 2>&1
    !pip install -q jupysql > /dev/null 2>&1

# Load SQL extension
%load_ext sql

# Config
%config SqlMagic.autopandas = True
pd.options.display.float_format = '{:.2f}'.format

In [4]:
import duckdb
import kagglehub
from pathlib import Path
import time

# Télécharger depuis Kaggle
print("📥 Téléchargement du dataset Kaggle...")
start_time = time.time()
dataset_path = kagglehub.dataset_download(
    "bhanuthakurr/cleaned-contoso-dataset"
)
download_time = time.time() - start_time
print(f"✓ Dataset téléchargé en {download_time:.2f}s\n")

# Créer une connexion DuckDB persistante
print("🔌 Création de la base DuckDB...")
con = duckdb.connect('accelerateur-sql.duckdb')
print("✓ Connecté!\n")

# Charger les fichiers CSV
print("📂 Chargement des données...")
csv_files = list(Path(dataset_path).glob('*.csv'))
print(f"📁 {len(csv_files)} fichiers CSV trouvés\n")

total_rows = 0
total_start = time.time()

for idx, csv_file in enumerate(csv_files, 1):
    table_name = csv_file.stem

    print(f"[{idx}/{len(csv_files)}] '{table_name}'...", end=" ", flush=True)

    # Charger directement avec DuckDB
    con.execute(f"""
        CREATE OR REPLACE TABLE {table_name} AS
        SELECT * FROM read_csv_auto('{csv_file}')
    """)

    # Compter les lignes
    row_count = con.execute(f"SELECT COUNT(*) FROM {table_name}").fetchone()[0]
    col_count = len(con.execute(f"SELECT * FROM {table_name} LIMIT 1").description)

    print(f"✓ ({row_count:,} lignes, {col_count} colonnes)")
    total_rows += row_count

total_time = time.time() - total_start

print("\n" + "=" * 60)
print(f"✓ COMPLET!")
print(f"  • Tables créées: {len(csv_files)}")
print(f"  • Lignes totales: {total_rows:,}")
print(f"  • Temps total: {total_time:.2f}s")
print("=" * 60)

📥 Téléchargement du dataset Kaggle...
Using Colab cache for faster access to the 'cleaned-contoso-dataset' dataset.
✓ Dataset téléchargé en 3.17s

🔌 Création de la base DuckDB...
✓ Connecté!

📂 Chargement des données...
📁 25 fichiers CSV trouvés

[1/25] 'FactSalesQuota'...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✓ (7,465,911 lignes, 10 colonnes)
[2/25] 'DimProductSubcategory'... ✓ (44 lignes, 3 colonnes)
[3/25] 'DimAccount'... ✓ (24 lignes, 6 colonnes)
[4/25] 'FactITSLA'... ✓ (4,925 lignes, 8 colonnes)
[5/25] 'DimMachine'... ✓ (7,816 lignes, 14 colonnes)
[6/25] 'FactOnlineSales'...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✓ (12,627,608 lignes, 18 colonnes)
[7/25] 'DimScenario'... ✓ (3 lignes, 2 colonnes)
[8/25] 'DimEmployee'... ✓ (293 lignes, 21 colonnes)
[9/25] 'DimProductCategory'... ✓ (8 lignes, 2 colonnes)
[10/25] 'DimStore'... ✓ (306 lignes, 16 colonnes)
[11/25] 'DimPromotion'... ✓ (28 lignes, 5 colonnes)
[12/25] 'DimOutage'... ✓ (303 lignes, 5 colonnes)
[13/25] 'DimEntity'... ✓ (421 lignes, 8 colonnes)
[14/25] 'DimCustomer'... ✓ (18,869 lignes, 15 colonnes)
[15/25] 'FactStrategyPlan'...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✓ (2,750,628 lignes, 8 colonnes)
[16/25] 'DimSalesTerritory'... ✓ (265 lignes, 10 colonnes)
[17/25] 'DimGeography'... ✓ (674 lignes, 6 colonnes)
[18/25] 'FactSales'...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✓ (3,406,089 lignes, 16 colonnes)
[19/25] 'DimProduct'... ✓ (2,233 lignes, 22 colonnes)
[20/25] 'FactInventory'...

FloatProgress(value=0.0, layout=Layout(width='auto'), style=ProgressStyle(bar_color='black'))

✓ (8,013,099 lignes, 13 colonnes)
[21/25] 'FactExchangeRate'... ✓ (773 lignes, 5 colonnes)
[22/25] 'DimCurrency'... ✓ (28 lignes, 3 colonnes)
[23/25] 'DimDate'... ✓ (2,556 lignes, 20 colonnes)
[24/25] 'DimChannel'... ✓ (4 lignes, 3 colonnes)
[25/25] 'FactITMachine'... ✓ (23,283 lignes, 5 colonnes)

============================================================
✓ COMPLET!
  • Tables créées: 25
  • Lignes totales: 34,326,191
  • Temps total: 84.98s
============================================================

In [5]:
%%sql con

In [6]:
%%sql
-- tester la ligne magique
SELECT * FROM FactOnlineSales
LIMIT 5

Running query in 'DuckDBPyConnection'

,OnlineSalesKey,DateKey,StoreKey,ProductKey,PromotionKey,CurrencyKey,CustomerKey,SalesOrderNumber,SalesOrderLineNumber,SalesQuantity,SalesAmount,ReturnQuantity,ReturnAmount,DiscountQuantity,DiscountAmount,TotalCost,UnitCost,UnitPrice
0,19560484,2007-01-01,306,782,10,1,333,20070101311332,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95
1,19560485,2007-01-01,306,782,10,1,334,20070101311333,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95
2,19560486,2007-01-01,306,782,10,1,335,20070101311334,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95
3,19560487,2007-01-01,306,782,10,1,336,20070101311335,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95
4,19560488,2007-01-01,306,782,10,1,337,20070101311336,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95

#Exercices

In [7]:
%%sql

-- ventes 2e semestre 2007

SELECT
  SUM(SalesAmount) AS total_sales_amount
FROM FactOnlineSales
WHERE DateKey >= '2007-07-01' AND DateKey <= '2007-12-31'

Running query in 'DuckDBPyConnection'

   total_sales_amount
0        490931085.28

In [8]:
%%sql

-- Ventes du 2ème semasetre 2007 ou du produit 782 (peu importe la date)

SELECT
  SUM(SalesAmount) AS total_sales_amount
FROM FactOnlineSales
WHERE (DateKey >= '2007-07-01' AND DateKey <= '2007-12-31') -- parenthèses pour meilleure lisibilité
OR ProductKey = 782

Running query in 'DuckDBPyConnection'

   total_sales_amount
0        490976418.57

In [9]:
%%sql


-- Ventes du produit 782 hors 2ème semestre 2007
SELECT
  SUM(SalesAmount) AS total_sales_amount
FROM FactOnlineSales
WHERE DateKey < '2007-07-01' OR DateKey > '2007-12-31' -- ici c'est donne moi toutes les ventes avant 2007-07-01 ET (les ventes après 2007-12-31 sur le produit 782)
AND ProductKey = 782

Running query in 'DuckDBPyConnection'

   total_sales_amount
0        519912180.48

In [10]:
%%sql

-- Ventes du produit 782 hors 2ème semestre 2007
-- Version correcte
-- Le AND s'exécute avant le OR

SELECT
  SUM(SalesAmount) AS total_sales_amount
FROM FactOnlineSales
WHERE (DateKey < '2007-07-01' OR DateKey > '2007-12-31') -- parenthèses pour meilleure lisibilité
AND ProductKey = 782

Running query in 'DuckDBPyConnection'

   total_sales_amount
0            45333.29

In [11]:
%%sql

-- Avec BETWEEN

SELECT
  SUM(SalesAmount) AS total_sales_amount
FROM FactOnlineSales
WHERE ProductKey = 782
AND DateKey NOT BETWEEN '2007-07-01' AND '2007-12-31'

Running query in 'DuckDBPyConnection'

   total_sales_amount
0            45333.29

## Exercices intermédiaires

In [15]:
%%sql
-- vente par magasin par identifiant

SELECT
  StoreKey,
  SUM(SalesAmount) AS total_sales_amount
FROM FactOnlineSales
GROUP BY StoreKey

Running query in 'DuckDBPyConnection'

   StoreKey  total_sales_amount
0       199       1031261452.79
1       306        837356228.18
2       307        849584948.83

In [16]:
%%sql

SELECT * FROM DimStore
LIMIT 5

Running query in 'DuckDBPyConnection'

,StoreKey,GeographyKey,StoreManager,StoreType,StoreName,Status,OpenDate,CloseDate,EntityKey,StorePhone,StoreFax,CloseReason,EmployeeCount,SellingAreaSize,LastRemodelDate,EmployeeKey
0,1,693,35,Store,Contoso Seattle No.1 Store,On,2004-04-12,2090-12-31,635,320-555-0195,320-555-0195,Not Yet Closed,17,462,2009-06-16,35
1,2,693,35,Store,Contoso Seattle No.2 Store,On,2004-02-14,2090-12-31,636,150-555-0189,150-555-0189,Not Yet Closed,25,700,2009-06-17,35
2,3,856,36,Store,Contoso Kennewick Store,On,2004-02-12,2090-12-31,934,212-555-0187,212-555-0187,Not Yet Closed,26,680,2009-06-18,36
3,4,424,37,Store,Contoso Bellevue Store,On,2004-03-01,2090-12-31,638,612-555-0100,612-555-0100,Not Yet Closed,19,455,2009-06-16,37
4,5,677,38,Store,Contoso Redmond Store,On,2004-04-02,2090-12-31,639,612-555-0100,612-555-0100,Not Yet Closed,33,560,2009-06-17,38

In [12]:
%%sql
--vente par magasin
-- Le directeur commercial : " j'ai besoin de savoir quels sont les magasins qui performent le mieux.
-- Peux tu me sortir le CA par magasin ? "

SELECT
  StoreName,
  SUM(SalesAmount) AS total_sales_amount
FROM FactOnlineSales
INNER JOIN DimStore
-- ON FactOnlineSales.StoreKey = DimStore.StoreKey
USING(StoreKey) -- quand ID est identique dans les 2 tables
GROUP BY StoreName
ORDER BY total_sales_amount DESC

Running query in 'DuckDBPyConnection'

                            StoreName  total_sales_amount
0  Contoso North America Online Store       1031261452.79
1           Contoso Asia Online Store        849584948.83
2         Contoso Europe Online Store        837356228.18

In [17]:
%%sql

-- Le directeur commercial: " C'est bien les magasins mais je veux comprendre d'où viennent
-- les clients par zone géographique"
-- vente par zone géo
SELECT
  RegionCountryName,
  SUM(SalesAmount) AS total_sales_amount
FROM FactOnlineSales
INNER JOIN DimStore
-- ON FactOnlineSales.StoreKey = DimStore.StoreKey
USING(StoreKey)
INNER JOIN DimGeography
USING(GeographyKey)
GROUP BY RegionCountryName
ORDER BY total_sales_amount DESC

Running query in 'DuckDBPyConnection'

  RegionCountryName  total_sales_amount
0     United States       1031261452.79
1             China        849584948.83
2           Germany        837356228.18

In [18]:
%%sql

SELECT * FROM DimGeography
LIMIT 5

Running query in 'DuckDBPyConnection'

,GeographyKey,GeographyType,ContinentName,CityName,StateProvinceName,RegionCountryName
0,1,Continent,Asia,None,None,None
1,2,Continent,Europe,None,None,None
2,3,Continent,North America,None,None,None
3,269,Country/Region,Asia,None,None,Armenia
4,270,Country/Region,Asia,None,None,Australia

## Exercice avancée

In [19]:
%%sql

SELECT * FROM FactOnlineSales
LIMIT 5

Running query in 'DuckDBPyConnection'

,OnlineSalesKey,DateKey,StoreKey,ProductKey,PromotionKey,CurrencyKey,CustomerKey,SalesOrderNumber,SalesOrderLineNumber,SalesQuantity,SalesAmount,ReturnQuantity,ReturnAmount,DiscountQuantity,DiscountAmount,TotalCost,UnitCost,UnitPrice
0,19560484,2007-01-01,306,782,10,1,333,20070101311332,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95
1,19560485,2007-01-01,306,782,10,1,334,20070101311333,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95
2,19560486,2007-01-01,306,782,10,1,335,20070101311334,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95
3,19560487,2007-01-01,306,782,10,1,336,20070101311335,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95
4,19560488,2007-01-01,306,782,10,1,337,20070101311336,1,1,10.36,0,0.00,1,2.59,6.60,6.60,12.95

In [25]:
%%sql
-- les clients qui génèrent le plus de CA
SELECT
 CustomerKey, FirstName, LastName,
 SUM(SalesAmount) AS total_sales_amount,
FROM FactOnlineSales
INNER JOIN DimCustomer
USING(CustomerKey)
GROUP BY CustomerKey, FirstName, LastName,
ORDER BY SUM(SalesAmount) DESC
LIMIT 5

Running query in 'DuckDBPyConnection'

   CustomerKey     FirstName      LastName  total_sales_amount
0        19053  Not Provided  Not Provided         19130453.28
1        19040  Not Provided  Not Provided         18599373.17
2        19041  Not Provided  Not Provided         18387863.33
3        19051  Not Provided  Not Provided         18268990.11
4        19043  Not Provided  Not Provided         18195922.77

In [21]:
%%sql

SELECT * FROM DimCustomer
LIMIT 5

Running query in 'DuckDBPyConnection'

,column00,CustomerKey,GeographyKey,FirstName,LastName,BirthDate,MaritalStatus,Gender,YearlyIncome,TotalChildren,NumberChildrenAtHome,Education,Occupation,HouseOwnerFlag,NumberCarsOwned
0,0,1,680,Jon,Yang,1966-04-08,M,M,90000.00,2.00,0.00,Bachelors,Professional,1.00,0.00
1,1,2,692,Eugene,Huang,1965-05-14,S,M,60000.00,3.00,3.00,Bachelors,Professional,0.00,1.00
2,2,3,493,Ruben,Torres,1965-08-12,M,M,60000.00,3.00,3.00,Bachelors,Professional,1.00,1.00
3,3,4,519,Christy,Zhu,1968-02-15,S,F,70000.00,0.00,0.00,Bachelors,Professional,0.00,1.00
4,4,5,706,Elizabeth,Johnson,1968-08-08,S,F,80000.00,5.00,5.00,Bachelors,Professional,1.00,4.00

In [ ]:
%%sql

-- identifier les clients qui ont acheté les produits les plus populaires:

-- le plus populaire en CA
-- le plus populaire en quantité

-- les clients qui ont acheté les 10 produits les plus populaires en CA
-- les clients qui ont acheté les 3 produits les plus populaires en CA

In [32]:
%%sql

-- les clients qui ont acheté les 3 produits les plus populaires en CA

-- 1/ identfier les 3 meilleurs produits en terme de CA
-- 2/ trouver les clients qui ont acheté les 3 meilleurs produits

SELECT
  ProductKey
FROM FactOnlineSales
GROUP BY ProductKey
ORDER BY SUM(SalesAmount) DESC
LIMIT 3

Running query in 'DuckDBPyConnection'

   ProductKey
0         153
1        1052
2        1293

In [33]:
%%sql

--  trouver les clients qui ont acheté les 3 meilleurs produits

WITH three_best_products AS (
  SELECT
    ProductKey
  FROM FactOnlineSales
  GROUP BY ProductKey
  ORDER BY SUM(SalesAmount) DESC
  LIMIT 3
)

SELECT
  CustomerKey,
  ProductKey
FROM FactOnlineSales
WHERE ProductKey IN (SELECT * FROM three_best_products)
GROUP BY CustomerKey, ProductKey
ORDER BY CustomerKey, ProductKey

Running query in 'DuckDBPyConnection'

       CustomerKey  ProductKey
0                2         153
1                2        1052
2                2        1293
3                3         153
4                3        1052
...            ...         ...
56101        19143        1293
56102        19144         153
56103        19145         153
56104        19145        1052
56105        19145        1293

[56106 rows x 2 columns]

In [37]:
%%sql
WITH three_best_products AS (
  SELECT
    ProductKey
  FROM FactOnlineSales
  GROUP BY ProductKey
  ORDER BY SUM(SalesAmount) DESC
  LIMIT 3
)

, customers_bought_three_products AS (
  -- customers who bought at least one of 3 best products
SELECT
  CustomerKey,
  ProductKey,
 -- COUNT(FactOnlineSales) AS times_bought
FROM FactOnlineSales
WHERE ProductKey IN (SELECT * FROM three_best_products)
GROUP BY CustomerKey, ProductKey -- car COUNT
ORDER BY CustomerKey, ProductKey
)  --donne les client qui ont acheté au moins des produits du top 3

SELECT
  CustomerKey,
FROM customers_bought_three_products
GROUP BY CustomerKey
HAVING COUNT(ProductKey) = 3
ORDER BY CustomerKey

Running query in 'DuckDBPyConnection'

       CustomerKey
0                2
1                3
2                4
3                5
4                6
...            ...
18590        19137
18591        19138
18592        19140
18593        19143
18594        19145

[18595 rows x 1 columns]

In [36]:
%%sql
WITH three_best_products AS (
  SELECT
    ProductKey
  FROM FactOnlineSales
  GROUP BY ProductKey
  ORDER BY SUM(SalesAmount) DESC
  LIMIT 3
)

, customers_bought_three_products AS (
  -- customers who bought at least one of 3 best products
SELECT
  FactOnlineSales.CustomerKey,
  FactOnlineSales.ProductKey
FROM FactOnlineSales
INNER JOIN three_best_products
ON FactOnlineSales.ProductKey = three_best_products.ProductKey
GROUP BY FactOnlineSales.CustomerKey, FactOnlineSales.ProductKey
ORDER BY FactOnlineSales.CustomerKey
)

SELECT
  CustomerKey,
FROM customers_bought_three_products
GROUP BY CustomerKey
HAVING COUNT(ProductKey) = 3
ORDER BY CustomerKey

-- donne les clients qui ont acheté les 3 produits

Running query in 'DuckDBPyConnection'

       CustomerKey
0                2
1                3
2                4
3                5
4                6
...            ...
18590        19137
18591        19138
18592        19140
18593        19143
18594        19145

[18595 rows x 1 columns]

In [43]:
%%sql

-- avec INNER JOIN

WITH three_best_products AS (
  SELECT
    ProductKey
  FROM FactOnlineSales
  GROUP BY ProductKey
  ORDER BY SUM(SalesAmount) DESC
  LIMIT 3
)

, customers_bought_three_products AS (
  -- customers who bought at least one of 3 best products
SELECT
  FactOnlineSales.CustomerKey,
  FactOnlineSales.ProductKey
FROM FactOnlineSales
INNER JOIN three_best_products
ON FactOnlineSales.ProductKey = three_best_products.ProductKey
GROUP BY FactOnlineSales.CustomerKey, FactOnlineSales.ProductKey  -- enlève les doublons
ORDER BY FactOnlineSales.CustomerKey
)

SELECT
  CustomerKey,
FROM customers_bought_three_products
GROUP BY CustomerKey
HAVING COUNT(ProductKey) = 3
ORDER BY CustomerKey

Running query in 'DuckDBPyConnection'

       CustomerKey
0                2
1                3
2                4
3                5
4                6
...            ...
18590        19137
18591        19138
18592        19140
18593        19143
18594        19145

[18595 rows x 1 columns]